/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form1;

/**
 *
 * @author Chamodi
 */
public class ThirdForm extends javax.swing.JFrame {

    /**
     * Creates new form ThirdForm
     */
    public ThirdForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnElders = new javax.swing.JButton();
        btnStaff = new javax.swing.JButton();
        btnAttendence = new javax.swing.JButton();
        btnMeals = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnElders.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnElders.setText("Elders details");
        btnElders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEldersActionPerformed(evt);
            }
        });
        getContentPane().add(btnElders, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 198, -1));

        btnStaff.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnStaff.setText("Staff Details");
        btnStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaffActionPerformed(evt);
            }
        });
        getContentPane().add(btnStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 198, -1));

        btnAttendence.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAttendence.setText("Manual Attendence");
        btnAttendence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttendenceActionPerformed(evt);
            }
        });
        getContentPane().add(btnAttendence, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, -1, -1));

        btnMeals.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnMeals.setText("Meals Details");
        btnMeals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMealsActionPerformed(evt);
            }
        });
        getContentPane().add(btnMeals, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 198, -1));

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chamodi\\Pictures\\Saved Pictures\\pngtree-elderly-care-services-hand-drawn-cartoon-flat-illustration-with-caregiver-png-image_6371595.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffActionPerformed
       new StaffDetailsView().show();
       this.hide();
        
        
    }//GEN-LAST:event_btnStaffActionPerformed

    private void btnAttendenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttendenceActionPerformed
         new AttendanceView().show();
         this.hide();
        
    }//GEN-LAST:event_btnAttendenceActionPerformed

    private void btnEldersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEldersActionPerformed
         new ParentDetailsView().show();
         this.hide();
        
        
    }//GEN-LAST:event_btnEldersActionPerformed

    private void btnMealsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMealsActionPerformed
        new MealsDetails().show();
        this.hide();
    }//GEN-LAST:event_btnMealsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
            new FirstForm().show();
            this.hide();
        
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThirdForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThirdForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThirdForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThirdForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThirdForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAttendence;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnElders;
    private javax.swing.JButton btnMeals;
    private javax.swing.JButton btnStaff;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
